esphome:
  name: bigbattery
  friendly_name: Big Battery
  comment: "AFERIY 3840Wh Portable Power Station"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "(PLACE YOU KEY HERE)"

ota:
  - platform: esphome
    password: "(PLACE YOU KEY HERE)"

# This assumed you put your WIFI SSID and passing in the secrets file
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: WARN

# Load external component from local path
external_components:
  - source: github://ylianst/esp-fbot
    refresh: 10s

# BLE Client configuration
ble_client:
  - mac_address: "AA:BB:CC:DD:EE:FF"  # Replace with your Fossibot MAC address

# Configure the Fbot component. This component will inherit the ble_client above.
fbot:
  id: my_fbot
  polling_interval: 5s  # How often to poll for updates (default: 2s)

# Binary sensors for connection and output states
binary_sensor:
  - platform: fbot
    fbot_id: my_fbot
    connected:
      name: "Connected"
      id: connected
      on_state:
        then:
          # When connection state changes, update the LED
          - script.execute: update_led
    # Optional sensors to indicate if the extra batteries 1 is connected
    #battery_connected_s1:
    #  name: "Connected S1"
    # Optional sensors to indicate if the extra batteries 2 is connected
    #battery_connected_s2:
    #  name: "Connected S2"
    usb_active:
      internal: true
      name: "USB Active"
    dc_active:
      internal: true
      name: "DC Active"
    ac_active:
      internal: true
      name: "AC Inverter Active"
      id: ac_active
      on_state:
        then:
          # When AC state changes, update the LED
          - script.execute: update_led
    light_active:
      internal: true
      name: "Light Active"
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: M5Atom Button
    internal: true
    on_press:
      then:
      - switch.toggle: light_switch

# Sensors for battery and power readings
sensor:
  - platform: fbot
    fbot_id: my_fbot
    battery_level:
      name: "Battery"
      id: battery_percent
      on_value:
        then:
          # When battery level changes, update the LED
          - script.execute: update_led
    # Optional sensors for the state of charge of extra battery 1
    #battery_s1_level:
    #  name: "Battery S1"
    #  id: battery_percent_s1
    # Optional sensors for the state of charge of extra battery 2
    #battery_s2_level:
    #  name: "Battery S2"
    #  id: battery_percent_s2
    input_power:
      name: "Input Power"
      id: input_watts
    output_power:
      name: "Output Power"
      id: output_watts
    system_power:
      name: "System Power"
      id: system_watts
    total_power:
      name: "Total Power"
      id: total_watts
    remaining_time:
      internal: true
      name: "Remaining Minutes"
      id: remaining_minutes
    # Optional sensors for charge/discharge thresholds
    threshold_charge:
      name: "Charge Threshold"
      id: threshold_charge
    threshold_discharge:
      name: "Discharge Threshold"
      id: threshold_discharge
  # Convert remaining time from minutes to hours
  - platform: template
    name: "Remaining Hours"
    lambda: |-
      if (id(remaining_minutes).has_state()) {
        return id(remaining_minutes).state / 60.0;
      }
      return 0.0;
    unit_of_measurement: "h"
    accuracy_decimals: 1
    device_class: duration
    state_class: measurement
    update_interval: 5s
  # Net power (positive = charging, negative = discharging)
  - platform: template
    name: "Net Power"
    lambda: |-
      if (id(input_watts).has_state() && id(output_watts).has_state()) {
        return id(input_watts).state - id(output_watts).state;
      }
      return 0.0;
    unit_of_measurement: "W"
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    update_interval: 5s

# Script to update LED based on connection, AC state, and battery level
script:
  - id: update_led
    then:
      - if:
          condition:
            binary_sensor.is_off: connected
          then:
            # Battery not connected - show white
            - light.turn_on:
                id: status_led
                red: 100%
                green: 100%
                blue: 100%
                brightness: 50%
          else:
            # Battery is connected
            - if:
                condition:
                  binary_sensor.is_off: ac_active
                then:
                  # AC not active - turn off LED
                  - light.turn_off: status_led
                else:
                  # AC is active - show battery level
                  - if:
                      condition:
                        lambda: 'return id(battery_percent).state > 30;'
                      then:
                        # Green for > 30%
                        - light.turn_on:
                            id: status_led
                            red: 0%
                            green: 100%
                            blue: 0%
                            brightness: 50%
                  - if:
                      condition:
                        lambda: 'return id(battery_percent).state > 15 && id(battery_percent).state <= 30;'
                      then:
                        # Yellow for 15-30%
                        - light.turn_on:
                            id: status_led
                            red: 100%
                            green: 100%
                            blue: 0%
                            brightness: 50%
                  - if:
                      condition:
                        lambda: 'return id(battery_percent).state <= 15;'
                      then:
                        # Red for <= 15%
                        - light.turn_on:
                            id: status_led
                            red: 100%
                            green: 0%
                            blue: 0%
                            brightness: 50%

# RGB LED on M5 ATOM (Pin 27, WS2812B)
light:
  - platform: esp32_rmt_led_strip
    internal: true
    chipset: WS2812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: "M5Atom Status LED"
    default_transition_length: 0.5s
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 1s
          update_interval: 1s

# Switches to control outputs
switch:
  - platform: fbot
    fbot_id: my_fbot
    usb:
      name: "USB Output"
      id: usb_switch
    dc:
      name: "DC Output"
      id: dc_switch
    ac:
      name: "AC Inverter"
      id: ac_switch
    light:
      name: "Light"
      id: light_switch

# Number controls for charge/discharge thresholds
number:
  - platform: fbot
    fbot_id: my_fbot
    # Charge threshold: stop charging when battery reaches this level (60-100%)
    threshold_charge:
      name: "Charge Max"
      min_value: 60
      max_value: 100
      step: 1
    # Discharge threshold: stop discharging when battery reaches this level (0-50%)
    threshold_discharge:
      name: "Discharge Min"
      min_value: 0
      max_value: 50
      step: 1
